<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PackageSeeder extends Seeder
{
    public function run()
    {
        $packages = [
            // ═══ WEBSITE PACKAGES ═══
            [
                'category' => 'website',
                'name' => 'Landing Page',
                'slug' => 'landing-page',
                'price' => 500000,
                'is_custom_price' => 0,
                'description' => 'Single page professional website with modern design, responsive layout, and SEO optimization.',
                'features' => json_encode([
                    '1 Halaman responsive',
                    'Desain modern & premium',
                    'SEO Basic',
                    'Free domain .com (1 tahun)',
                    'Free hosting (1 tahun)',
                    'SSL Certificate',
                    'Contact form',
                    '3x Revisi',
                ]),
                'duration_days' => 7,
                'max_revisions' => 3,
                'is_active' => 1,
                'sort_order' => 1,
            ],
            [
                'category' => 'website',
                'name' => 'Company Profile',
                'slug' => 'company-profile',
                'price' => 1500000,
                'is_custom_price' => 0,
                'description' => 'Multi-page professional company profile with admin panel to manage content.',
                'features' => json_encode([
                    '5-7 Halaman responsive',
                    'Admin panel (CMS)',
                    'Desain custom premium',
                    'SEO Optimization',
                    'Free domain .com (1 tahun)',
                    'Free hosting (1 tahun)',
                    'SSL Certificate',
                    'Contact form + Google Maps',
                    'Social media integration',
                    '5x Revisi',
                ]),
                'duration_days' => 14,
                'max_revisions' => 5,
                'is_active' => 1,
                'sort_order' => 2,
            ],
            [
                'category' => 'website',
                'name' => 'E-Commerce',
                'slug' => 'e-commerce',
                'price' => 3500000,
                'is_custom_price' => 0,
                'description' => 'Full-featured online store with payment gateway, inventory management, and admin dashboard.',
                'features' => json_encode([
                    'Unlimited halaman produk',
                    'Shopping cart & checkout',
                    'Payment gateway (Midtrans)',
                    'Admin panel lengkap',
                    'Inventory management',
                    'Order tracking',
                    'Customer accounts',
                    'Free domain .com (1 tahun)',
                    'Free hosting (1 tahun)',
                    'SSL Certificate',
                    'SEO Optimization',
                    '7x Revisi',
                ]),
                'duration_days' => 30,
                'max_revisions' => 7,
                'is_active' => 1,
                'sort_order' => 3,
            ],
            [
                'category' => 'website',
                'name' => 'Custom Web Application',
                'slug' => 'custom-web-app',
                'price' => 0,
                'is_custom_price' => 1,
                'description' => 'Fully customized web application built to your exact specifications. Price based on project scope and complexity.',
                'features' => json_encode([
                    'Custom design & development',
                    'Fitur sesuai kebutuhan',
                    'Konsultasi gratis',
                    'Arsitektur scalable',
                    'API development',
                    'Third-party integration',
                    'Free domain & hosting (1 tahun)',
                    'Revisi sesuai kesepakatan',
                ]),
                'duration_days' => 60,
                'max_revisions' => 10,
                'is_active' => 1,
                'sort_order' => 4,
            ],

            // ═══ MOBILE APP PACKAGES ═══
            [
                'category' => 'mobile',
                'name' => 'Basic Mobile App',
                'slug' => 'basic-mobile-app',
                'price' => 5000000,
                'is_custom_price' => 0,
                'description' => 'Simple mobile application with essential features for Android & iOS using Flutter.',
                'features' => json_encode([
                    'Android & iOS (Flutter)',
                    'Up to 5 screens',
                    'UI/UX Design',
                    'Basic API integration',
                    'Push notifications',
                    'User authentication',
                    'Source code included',
                    '5x Revisi',
                ]),
                'duration_days' => 30,
                'max_revisions' => 5,
                'is_active' => 1,
                'sort_order' => 1,
            ],
            [
                'category' => 'mobile',
                'name' => 'Full Mobile App',
                'slug' => 'full-mobile-app',
                'price' => 15000000,
                'is_custom_price' => 0,
                'description' => 'Full-featured mobile application with complex business logic, backend API, and admin panel.',
                'features' => json_encode([
                    'Android & iOS (Flutter/React Native)',
                    'Unlimited screens',
                    'Custom UI/UX Design',
                    'Backend API development',
                    'Admin panel / dashboard',
                    'Payment integration',
                    'Real-time features',
                    'Analytics dashboard',
                    'Source code included',
                    'Play Store & App Store publish',
                    '10x Revisi',
                ]),
                'duration_days' => 60,
                'max_revisions' => 10,
                'is_active' => 1,
                'sort_order' => 2,
            ],
            [
                'category' => 'mobile',
                'name' => 'Custom Mobile Solution',
                'slug' => 'custom-mobile',
                'price' => 0,
                'is_custom_price' => 1,
                'description' => 'Enterprise-grade mobile solution tailored to your business needs. Price based on scope.',
                'features' => json_encode([
                    'Native (Kotlin/Swift) atau cross-platform',
                    'Fitur enterprise-grade',
                    'IoT integration',
                    'AI/ML features',
                    'Custom backend',
                    'Dedicated project manager',
                    'Maintenance support',
                ]),
                'duration_days' => 90,
                'max_revisions' => 15,
                'is_active' => 1,
                'sort_order' => 3,
            ],

            // ═══ CONSULTING PACKAGES ═══
            [
                'category' => 'consulting',
                'name' => 'Konsultasi 1 Jam',
                'slug' => 'konsultasi-1-jam',
                'price' => 200000,
                'is_custom_price' => 0,
                'description' => 'One-on-one consultation session with our tech expert to discuss your project ideas and strategy.',
                'features' => json_encode([
                    '1 jam sesi konsultasi',
                    'Video call / Meeting',
                    'Tech stack recommendation',
                    'Project estimation',
                    'Summary report',
                ]),
                'duration_days' => 1,
                'max_revisions' => 0,
                'is_active' => 1,
                'sort_order' => 1,
            ],
            [
                'category' => 'consulting',
                'name' => 'Paket Konsultasi Bulanan',
                'slug' => 'konsultasi-bulanan',
                'price' => 1500000,
                'is_custom_price' => 0,
                'description' => 'Monthly tech consulting package with regular sessions, code review, and strategic guidance.',
                'features' => json_encode([
                    '4x sesi konsultasi/bulan',
                    'Code review',
                    'Architecture review',
                    'Tech strategy planning',
                    'Priority WhatsApp support',
                    'Monthly progress report',
                ]),
                'duration_days' => 30,
                'max_revisions' => 0,
                'is_active' => 1,
                'sort_order' => 2,
            ],
            [
                'category' => 'consulting',
                'name' => 'Full Tech Audit',
                'slug' => 'tech-audit',
                'price' => 3000000,
                'is_custom_price' => 0,
                'description' => 'Comprehensive technical audit of your existing systems with detailed recommendations.',
                'features' => json_encode([
                    'Full code audit',
                    'Security assessment',
                    'Performance analysis',
                    'Architecture review',
                    'Detailed report + recommendations',
                    'Implementation roadmap',
                    'Follow-up consultation',
                ]),
                'duration_days' => 14,
                'max_revisions' => 0,
                'is_active' => 1,
                'sort_order' => 3,
            ],
        ];

        foreach ($packages as $package) {
            $this->db->table('service_packages')->insert($package);
        }
    }
}
